# Trabajo Grupal - Análisis de datos - 2026 B1

## Grupo 4 - Eventos de Violencia Organizada
- Pedro Ignacio Rubiolo
- Lourdes Sofia Tolotto
- Manuel Dieguez
- Santiago Federico Bettig
## Secciones
- Inicio
- EDA
- Visualizacion
- Plantear Problema de ML
- Preprocesamiento y Limpieza
- Feature Engineering
- Reduccion de Dimensionalidad

## Inicio

In [28]:
#Imports
import pandas as pd

In [37]:
#Config
pd.set_option('display.max_columns', None)

In [ ]:
#Carga del dataset completo
df = pd.read_csv("GEDEvent_v25_1.csv")

/tmp/ipykernel_21398/348982334.py:1: DtypeWarning: Columns (47) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("GEDEvent_v25_1.csv")

## EDA

### Objetivos
- Cargar el dataset proporcionado y realizar un análisis exploratorio de los datos. 
- Describir las características principales del dataset, incluyendo el número de 
observaciones, número de variables y tipos de datos. 
- Identificar patrones generales y distribuciones.  
- Identificar errores, outliers (anomalías), valores faltantes y su tipo (MCAR, MAR, 
MNAR).

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 385918 entries, 0 to 385917
Data columns (total 49 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 385918 non-null  int64
 1   relid              385918 non-null  object
 2   year               385918 non-null  int64
 3   active_year        385918 non-null  bool
 4   code_status        385918 non-null  object
 5   type_of_violence   385918 non-null  int64
 6   conflict_dset_id   385918 non-null  int64
 7   conflict_new_id    385918 non-null  int64
 8   conflict_name      385918 non-null  object
 9   dyad_dset_id       385918 non-null  int64
 10  dyad_new_id        385918 non-null  int64
 11  dyad_name          385918 non-null  object
 12  side_a_dset_id     385918 non-null  int64
 13  side_a_new_id      385918 non-null  int64
 14  side_a             385918 non-null  object
 15  side_b_dset_id     385918 non-null  int64
 16  side_b_new_id      385918 non-null  int64
 17  side_b             385918 non-null  object
 18  number_of_sources  385918 non-null  int64
 19  source_article     385917 non-null  object
 20  source_office      288005 non-null  object
 21  source_date        288005 non-null  object
 22  source_headline    288000 non-null  object
 23  source_original    341674 non-null  object
 24  where_prec         385918 non-null  int64
 25  where_coordinates  385918 non-null  object
 26  where_description  375675 non-null  object
 27  adm_1              366371 non-null  object
 28  adm_2              315941 non-null  object
 29  latitude           385918 non-null  float64
 30  longitude          385918 non-null  float64
 31  geom_wkt           385918 non-null  object
 32  priogrid_gid       385918 non-null  int64
 33  country            385918 non-null  object
 34  country_id         385918 non-null  int64
 35  region             385918 non-null  object
 36  event_clarity      385918 non-null  int64
 37  date_prec          385918 non-null  int64
 38  date_start         385918 non-null  object
 39  date_end           385918 non-null  object
 40  deaths_a           385918 non-null  int64
 41  deaths_b           385918 non-null  int64
 42  deaths_civilians   385918 non-null  int64
 43  deaths_unknown     385918 non-null  int64
 44  best               385918 non-null  int64
 45  high               385918 non-null  int64
 46  low                385918 non-null  int64
 47  gwnoa              292507 non-null  object
 48  gwnob              30256 non-null   float64
dtypes: bool(1), float64(3), int64(24), object(21)
memory usage: 141.7+ MB

In [38]:
df.head()

,id,relid,year,active_year,code_status,type_of_violence,conflict_dset_id,conflict_new_id,conflict_name,dyad_dset_id,dyad_new_id,dyad_name,side_a_dset_id,side_a_new_id,side_a,side_b_dset_id,side_b_new_id,side_b,number_of_sources,source_article,source_office,source_date,source_headline,source_original,where_prec,where_coordinates,where_description,adm_1,adm_2,latitude,longitude,geom_wkt,priogrid_gid,country,country_id,region,event_clarity,date_prec,date_start,date_end,deaths_a,deaths_b,deaths_civilians,deaths_unknown,best,high,low,gwnoa,gwnob
0,244657,IRQ-2017-1-524-322,2017,True,Clear,1,259,259,Iraq: Government,524,524,Government of Iraq - IS,116,116,Government of Iraq,234,234,IS,3,"""Agence France Presse,2017-08-01,At least 20 k...",Agence France Presse;Agence France Presse;Pajh...,2017-08-01;2017-08-01;2017-07-31,At least 20 killed in Shiite mosque attack in ...,"IS, interior ministry, security source",1,Kabul city,Iraqi embassy in Kabul,Kabul province,Kabul district,34.531094,69.162796,POINT (69.162796 34.531094),179779,Afghanistan,700,Asia,1,1,2017-07-31 00:00:00.000,2017-07-31 00:00:00.000,0,4,0,2,6,6,6,645,NaN
1,412700,IRQ-2021-1-524-145,2021,True,Clear,1,259,259,Iraq: Government,524,524,Government of Iraq - IS,116,116,Government of Iraq,234,234,IS,15,"""BBC News,2021-08-26,Explosion at Kabul airpor...",BBC News;ShamshadNews on Twitter;Xinhua News A...,2021-08-26;2021-08-26;2021-08-30;2021-08-27;20...,Explosion at Kabul airport;At least 11 people ...,US officials; Taliban spokesman Zabihullah Muj...,1,Kabul international airport,Kabul airport (Abbey gate entrance),Kabul province,Kabul district,34.564444,69.217222,POINT (69.2172222 34.5644444),179779,Afghanistan,700,Asia,1,1,2021-08-26 00:00:00.000,2021-08-26 00:00:00.000,13,1,141,28,183,184,171,645,NaN
2,413023,IRQ-2021-1-524-143,2021,True,Clear,1,259,259,Iraq: Government,524,524,Government of Iraq - IS,116,116,Government of Iraq,234,234,IS,5,"""Khaama Press,2021-08-28,First US airstrike hi...",Khaama Press;Reuters News;Agence France Presse...,2021-08-28;2021-08-28;2021-08-28;2021-08-28;20...,First US airstrike hits ISIS-K fighter after T...,US central command spokesperson Captain Bill U...,1,Jalalabad town,Police District 7 of Jalalabad city,Nangarhar province,Jalalabad district,34.428844,70.455750,POINT (70.45575 34.428844),179061,Afghanistan,700,Asia,1,1,2021-08-28 00:00:00.000,2021-08-28 00:00:00.000,0,2,0,0,2,3,0,645,NaN
3,412909,IRQ-2021-1-524-144,2021,True,Clear,1,259,259,Iraq: Government,524,524,Government of Iraq - IS,116,116,Government of Iraq,234,234,IS,8,"""CNN,2021-08-29,Nine family members, including...",CNN;Reuters News;Associated Press Newswires;BB...,2021-08-29;2021-08-29;2021-08-30;2021-08-31;20...,"Nine family members, including children, kille...",relative; US Central Command; witnesses; Afgha...,1,Kabul city,Kabul city (district 15),Kabul province,Kabul district,34.531094,69.162796,POINT (69.162796 34.531094),179779,Afghanistan,700,Asia,1,1,2021-08-29 00:00:00.000,2021-08-29 00:00:00.000,0,0,10,0,10,10,9,645,NaN
4,132140,AFG-1989-1-411-2,1989,True,Clear,1,333,333,Afghanistan: Government,724,724,Government of Afghanistan - Jam'iyyat-i Islami...,130,130,Government of Afghanistan,292,292,Jam'iyyat-i Islami-yi Afghanistan,-1,"The Times 13 Jan 1989 ""Missiles and tea breaks...",NaN,NaN,NaN,Rebel source,4,Nangarhar province,Nangarhar province,Nangarhar province,NaN,34.333330,70.416670,POINT (70.41667 34.33333),179061,Afghanistan,700,Asia,1,3,1989-01-07 00:00:00.000,1989-01-13 00:00:00.000,6,0,0,0,6,6,6,700,NaN

In [21]:
# Faltantes
missing_count = df.isna().sum()
missing_percentage = (df.isna().mean() * 100).round(2)

missing_summary = pd.DataFrame({
    'Cantidad': missing_count,
    'Porcentaje': missing_percentage
})

# Filtrar las que estan completas
missing_summary = missing_summary[missing_summary['Cantidad'] > 0]

# Ordenar en ascendente
missing_summary = missing_summary.sort_values(by='Cantidad', ascending=False)

missing_summary

                   Cantidad  Porcentaje
gwnob                355662       92.16
source_headline       97918       25.37
source_office         97913       25.37
source_date           97913       25.37
gwnoa                 93411       24.20
adm_2                 69977       18.13
source_original       44244       11.46
adm_1                 19547        5.07
where_description     10243        2.65
source_article            1        0.00

In [47]:
#Indagacion respecto de source_original pq no la comprendo del todo

df[["number_of_sources", "source_original"]].head(20)

    number_of_sources                                    source_original
0                   3             IS, interior ministry, security source
1                  15  US officials; Taliban spokesman Zabihullah Muj...
2                   5  US central command spokesperson Captain Bill U...
3                   8  relative; US Central Command; witnesses; Afgha...
4                  -1                                       Rebel source
5                  -1               Kabul radio (monitored in Islamabad)
6                  -1  Tass news agency /Western diplomats quoting wi...
7                  -1                                 Military spokesman
8                  -1                                    Rebel spokesman
9                  -1                                   Tass news agency
10                 -1                                   Tass news agency
11                 -1                 Soviet officials and media reports
12                 -1               Kabul radio (monitored in Islamabad)
13                 -1                  Afghan Foreign Ministry officials
14                 -1               Kabul radio (monitored in Islamabad)
15                 -1                                   Tass news agency
16                 -1                                                NaN
17                 -1  Rebel spokesman / Kabul radio /guerrilla-contr...
18                 -1                                   State television
19                 -1                                   Tass news agency

## Visualizacion

### Objetivos
- Utilizar técnicas de visualización adecuadas para ilustrar las principales 
características del dataset. 
- Asegurarse de que las visualizaciones sean claras, concisas y efectivas para 
comunicar la información. 
- Interpretar los resultados obtenidos a partir de las visualizaciones.

## Problema ML

### Objetivos
- Describir el problema de clasificación o de regresión. 
- Definir la variable target.

## Preprocesamiento y Limpieza

### Objetivos
- Realizar una limpieza general del dataset, eliminando o corrigiendo datos 
inconsistentes o irrelevantes. 
- Realizar el split del dataset (ej: train y test).  
- Identificar y tratar los valores faltantes en el dataset.
- Detectar y manejar los outliers utilizando técnicas estadísticas o visuales 
apropiadas. 
- Escalar y / o normalizar los features.

In [41]:
# Primer paso, limpieza de columnas que aportan info redundante o no relevante
cols_to_drop = [
    "id", # No sirve el identificador unico
    "relid", # Legacy
    "active_year", # No connsidero relevante si es un conflicto activo
    "code_status", # Siempre es clear
    "conflict_dset_id", # Legacy
    "conflict_new_id", # Mantener solo conflict_name
    "dyad_dset_id", # Legacy
    "dyad_new_id", # Mantener solo dyad_name
    "side_a_dset_id", # Legacy
    "side_a_new_id", # Usar solo side_a
    "side_b_dset_id", # Legacy
    "side_b_new_id", # Usar solo side_b
    "source_article", # No considero disponible
    "source_office", # No considero disponible
    "source_date", #No considero disponible
    "source_headline", #No considero disponible
    "where_description", #No considero patronizable
    "adm_1", # Redundante, con lat long
    "adm_2", # Redundante, con lat long
    "geom_wkt", # Redundante, con lat long
    "priogrid_gid", # Redundante, con lat long
    "country_id", # Usar solo country
    "event_clarity", # No considero disponible
    "date_prec", # No considero disponible
    "deaths_a", #Leakage
    "deaths_b", #Leakage
    "deaths_civilians", #Leakage
    "deaths_unknown", #Leakage
    "best", #Leakage
    "high", #Leakage
    "low", #Leakage
    "gwnoa", # Mantener solo side_a
    "gwnob", # Mantener solo side_b
]

small_df = df.drop(columns=cols_to_drop)

In [42]:
# Faltantes
missing_count = small_df.isna().sum()
missing_percentage = (small_df.isna().mean() * 100).round(2)

missing_summary = pd.DataFrame({
    'Cantidad': missing_count,
    'Porcentaje': missing_percentage
})

# Filtrar las que estan completas
missing_summary = missing_summary[missing_summary['Cantidad'] > 0]

# Ordenar en ascendente
missing_summary = missing_summary.sort_values(by='Cantidad', ascending=False)

missing_summary

                 Cantidad  Porcentaje
source_original     44244       11.46

In [51]:
small_df["source_original"].value_counts().head(50)

source_original
SOHR                                                                   37691
VDC                                                                    25457
police                                                                  9820
Noche y Niebla                                                          9223
SOHR; VDC                                                               8033
SOHR, VDC                                                               6367
UA Losses                                                               5661
SATP                                                                    4596
Russo-Ukrainian Warspotting                                             3238
Balkan Battlegrounds and Bosnian Book of the Dead - List of Victims     3216
Police                                                                  3162
CIDE-PPD                                                                2887
Kivu Security Tracker                                                   2587
Borderland Beat                                                         2572
Interior Ministry                                                       2498
MoD                                                                     2427
officials                                                               2292
El Sol de Tijuana                                                       2267
Balkan Battlegrounds; Bosnian Book of the Dead                          2235
NY Times                                                                1939
Memorybook                                                              1694
military                                                                1429
21YYTE                                                                  1424
Russian MoD                                                             1398
PROVEA                                                                  1291
Military                                                                1266
Police spokesman                                                        1217
Military spokesman                                                      1143
El Sol del Bajío                                                        1139
Ibuka                                                                   1127
military spokesman                                                      1064
CIMP                                                                     996
Officials                                                                986
Milenio                                                                  932
witnesses                                                                931
Taleban                                                                  927
Local official                                                           897
El Heraldo de Juárez                                                     891
Syrian Observatory for Human Rights                                      890
army                                                                     887
Btselem                                                                  873
AAPP                                                                     840
Defense Ministry                                                         793
wafa                                                                     791
El Sol de Acapulco                                                       788
Airwars                                                                  772
military sources                                                         763
Syrian Observatory for Human Rights, VDC                                 763
SOHR\nVDC                                                                752
Portal Tucumã                                                            733
Name: count, dtype: int64

## Feature Engineering

### Objetivos
- Crear nuevos features en caso de ser necesario. Justificar. 
- Aplicar técnicas de conversión de variables: codificación, discretización. 
- Analizar el balance/desbalance de clases (en el caso que se trate de un problema de clasificación). 
- Proponer y aplicar mecanismos de balance en caso de ser necesario y justificar la selección.

## Reduccion de Dimensionalidad

### Objetivos
- Evaluar relaciones entre variables y realizar una selección de features con los 
mecanismos vistos en clase (ej: filtros). 
- Implementar técnicas de extracción de features (ej: PCA). Evaluar ventajas y 
desventajas de la reducción.